### ISSUE TITLE
Using with StitchData

### ISSUE THREAD

**Issue by mikek03** [singer-io/tap-campaign-monitor#3]
Hi,

I've been trying this within StitchData to extract data from Campaign Monitor into a Data Warehouse.

It seems to work pretty well, but I am not sure if it's working quite as expected, particularly with the Campaign_Recipients table.

According to StitchData it has processed 445,785,133 rows from this table, but our table should only contain 3,619,650 rows, which have all been transferred to our DW.

It's as if it isn't fetching incremental rows, but instead fetching the entire 3.6mil rows every day.
My question is, should tap-campaign-monitor be fetching incrementally, or is it only a full extract each time it is run?

Thanks

Mike

**Comment by KAllan357** [comment]
@mikek03 I believe its a full extract each time its executed. Based on the [documentation here](https://www.campaignmonitor.com/api/campaigns/#campaign-recipients), I don't see a way to filter these results on a bookmark.

What I'd recommend from a Stitch perspective is to create two integrations with different schedules. Unfortunately even with a daily replication I suppose this Campaign Recipients table would still sync a great deal of data. Separating and pausing that integration might be the best bet for now.

**Comment by mikek03** [comment]
@KAllan357 thanks, I thought as much.  I suspect most of the data is replicated each time, just much smaller volumes.   This must be one heck of an overhead on Campaign Monitor's API!
